trigger:
  - master

strategy:
  matrix:
    linux_node_12:
      imageName: 'ubuntu-latest'
      node_version: 12.x
    mac_node_12:
      imageName: 'macos-10.13'
      node_version: 12.x
    mac_node_13:
      imageName: 'macos-10.13'
      node_version: 13.x

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node.js'

  - script: yarn && yarn add --dev -W webpack && yarn
    displayName: 'install dependencies with webpack 4'

  - script: yarn lerna run build:dev --sort
    displayName: 'running build:dev in all packages'

  - script: yarn lerna run clean
    displayName: 'cleaning dist folder in all packages'

  - script: yarn lerna run build:prod --sort
    displayName: 'running build:prod in all packages'

  - script: yarn lerna run clean
    displayName: 'cleaning dist folder in all packages'

  - script: yarn lerna run test
    displayName: 'running tests in all packages'

  - script: yarn add --dev -W webpack@next && yarn
    displayName: 'install webpack 5'

  - script: yarn lerna run build:dev --sort
    displayName: 'running build:dev in all packages'

  - script: yarn lerna run clean
    displayName: 'cleaning dist folder in all packages'

  - script: yarn lerna run build:prod --sort
    displayName: 'running build:prod in all packages'
