variables:
  - group: github-props

trigger:
  - master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
      node_version: 10.x
    mac:
      imageName: 'macos-10.13'
      node_version: 10.x

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node.js'

  - script: yarn
    displayName: 'install dependencies'

  - script: yarn lerna run build:dev --sort
    displayName: 'running build:dev in all packages'

  - script: yarn lerna run clean
    displayName: 'cleaning dist folder in all packages'

  - script: yarn lerna run build:prod
    displayName: 'running build:prod in all packages'

  - script: yarn lerna run clean
    displayName: 'cleaning dist folder in all packages'

  - script: yarn lerna run test
    displayName: 'running tests in all packages'
