trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      yarn --ignore-scripts
      yarn lerna run build:prod --sort
    displayName: 'yarn && lerna build:prod --sort'
